# This file is meant to provide a quick way to get the project up and running
# It will create a docker container for the database and phpmyadmin
# Use phpmyadmin to create the database and import the sql file
# during the import disable `Enable foreign key checks`
version: '3'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - online-store-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

volumes:
  online-store-db:
